version: '3'

networks:
  snapovia:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - database
      - app
    networks:
      - snapovia


  database:
    image: mariadb:10.5.8
    container_name: mysqldb
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: snapoviadb
      MYSQL_USER: snapovia
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - snapovia

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: snapovia/php
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - snapovia

  npm:
    image: node:12-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', '--no-bin-links']
    networks:
      - snapovia

  redis:
    image: redis:alpine
    container_name: redisserver
    ports:
      - "6379:6379"
    networks:
      - snapovia
