version: '3'

networks:
  snapovia:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - snapovia


  mysql:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: butikshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - snapovia

  php:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - snapovia

  npm:
    image: node:12-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', '--no-bin-links']
    networks:
      - snapovia

  redis:
    image: redis:alpine
    container_name: redisserver
    ports:
      - "6379:6379"
    networks:
      - snapovia
