name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.test', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database & Seed test data
        run: |
          touch database/database.sqlite
          php artisan migrate:fresh --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/pest

  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Installing Composer dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: back-end
          php_version: 8.1
          php_extensions: imap pcntl xdebug zip
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Create Composer dependencies artifact
        uses: actions/upload-artifact@master
        with:
          name: vendors
          path: back-end/vendor
